logging:
  file:
    name: logs/shoply.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  tomcat:
    uri-encoding: utf-8
  port: 8080
  servlet:
    context-path: /shoply
spring:
  application:
    name: shoply
    version: ${version}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 175533324145-1bas44qullc0br7nh133gpi349jhcnhh.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://ec2-3-38-140-9.ap-northeast-2.compute.amazonaws.com:8080/shoply/login/oauth2/code/google
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 1234
    url: jdbc:oracle:thin:@//3.38.140.9:1522/XEPDB1
    username: shoply
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bisunesskyu@gmail.com
    password: detvitlhtcjlqtah
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  servlet:
    multipart:
      location: upload
      max-file-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:/home/ec2-user/shoply/uploads/

solapi:
  apiKey: NCSVE4XEUBWV80QH
  apiSecret: FVGCA9H20BAJJDXLOKMJ1EE9VXLTK8UW
  phoneNumber: 01033603234
